<a href="https://colab.research.google.com/github/karol10542/Podstawy_nauki_o_danych/blob/main/tworzenie_tablic_z_pakietu_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
list_of_ints = [1,2,3,4,5,6]

In [3]:
list_of_ints

[1, 2, 3, 4, 5, 6]

In [4]:
list_of_ints[0]

1

In [5]:
array_1 =np.array( list_of_ints)

In [6]:
array_1

array([1, 2, 3, 4, 5, 6])

In [7]:
type(array_1)

numpy.ndarray

In [8]:
#kontrolowanie ilosci zajmowanej pamieci
array_1.nbytes

48

In [9]:
#aby zmniejszyć ilosc zajmowanej pamieci nalezy dostoswac typ do tablicy
array_1 = np.array(list_of_ints,dtype="int8")

In [10]:
array_1.nbytes

6

In [11]:
#zmiana typu tablicy
array_1b = array_1.astype('float32')

###listy niejednorodne

In [12]:
complex_list = [1,2,3] + ['a','b','c'] + [1.,2.,3.]

In [13]:
complex_list

[1, 2, 3, 'a', 'b', 'c', 1.0, 2.0, 3.0]

In [14]:
array_2 = np.array(complex_list[:3])

In [15]:
print('complex_list[:3]',array_2.dtype)

complex_list[:3] int64


In [21]:
array_2 = np.array(complex_list[:6])

In [22]:
print('complex_list[:6]',array_2.dtype)

complex_list[:6] <U21


In [19]:
array_2 = np.array(complex_list[:])
print('complex_list[:]',array_2.dtype)


complex_list[:] <U21


In [23]:
#sprawdzanie czy tablica np zawiera dane odpowiedniego typu
print(isinstance(array_2[0],np.number))

False


##listy wielowymiarowe

In [24]:
a_list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]

In [25]:
array_2D = np.array(a_list_of_lists)

In [26]:
array_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
array_2D[1,1]

5

In [28]:
array_2D[1][1]

5

In [29]:
#listy trzywymiarowe
a_list_of_lists_of_lists = [[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]

In [30]:
array_3D = np.array(a_list_of_lists_of_lists)

In [31]:
array_3D

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [32]:
array_3D[0,2,0]

5

In [49]:
#zmiana tablicy z 1d na 2d i 3d
testlist1 = [1,2,3,4,5,6,7,8]
testlist = np.array(testlist1)

In [50]:
testlist

array([1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
list2d = testlist.reshape(4,2).copy

In [53]:
list2d

<function ndarray.copy>

In [55]:
list3d = testlist.reshape(2,2,2)

In [56]:
list3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [57]:
#tworzenie tablicy i uzupelnianie jej z pakietem np
list1 = np.arange(9).reshape(3,3)

In [58]:
list1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [83]:
#losowe uzupelnianie tablicy
randomlist = np.random.randint(low=1,high=10,size=(3,3)).reshape(3,3)

In [84]:
randomlist

array([[5, 6, 5],
       [2, 7, 7],
       [4, 5, 9]])

In [86]:
#wypełnianie tablicy zerami,jedynkami 
oneslist = np.ones((3,3))

In [87]:
oneslist

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [88]:
zeroslist = np.zeros((3,3))

In [89]:
zeroslist

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [90]:
eyelist = np.eye(3)

In [91]:
eyelist

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])